FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# quizapi

quiz is a simple API allowing for the interface with the solu quiz service.

## QuestionBank Collection [/questionbank]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
            "Title": "Question #1",
            "CreatedDate": "2015-01-01 00:00:00",
            "ModifiedDate": "2015-01-01 00:00:00",
            "CreatedBy": "Bob",
            "ModifiedBy": "Frank",
            "QuestionCategoryID": "1",
            "QuestionLevelID": "1",
            "QuestionTypeID": "1",
            "QuestionID": "1",
            "Approved": "-1"
            },
            {
            "Title": "Question #1",
            "CreatedDate": "2015-01-01 00:00:00",
            "ModifiedDate": "2015-01-01 00:00:00",
            "CreatedBy": "Bob",
            "ModifiedBy": "Frank",
            "QuestionCategoryID": "1",
            "QuestionLevelID": "1",
            "QuestionTypeID": "1",
            "QuestionID": "1",
            "Approved": "-1"
            }
        ]


### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "Title": "Question #1",
            "CreatedDate": "2015-01-01 00:00:00",
            "ModifiedDate": "2015-01-01 00:00:00",
            "CreatedBy": "Bob",
            "ModifiedBy": "Frank",
            "QuestionCategoryID": "1",
            "QuestionLevelID": "1",
            "QuestionTypeID": "1",
            "QuestionID": "1",
            "Approved": "-1"
            }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2


## Single Question [/questionbank/{id}]
### List Single Questions [GET]

+ Response 200 (application/json)

        [
            {
            "Title": "Question #1",
            "CreatedDate": "2015-01-01 00:00:00",
            "ModifiedDate": "2015-01-01 00:00:00",
            "CreatedBy": "Bob",
            "ModifiedBy": "Frank",
            "QuestionCategoryID": "1",
            "QuestionLevelID": "1",
            "QuestionTypeID": "1",
            "QuestionID": "1",
            "Approved": "-1"
            }
        ]